name: Technology & Science
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8f586508-cf95-4e5e-945b-97b1914a5635.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/596ef80a-2ab5-4c95-822d-d1feb6ce92c2.png
layout_spectrum: 0.23649111656619623
typography_spectrum: 0.4510947629966137
analytics:
  google: UA-79126334-1
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#725700'
    - '#FC2E8D'
    - '#E6B600'
  brandStrength: 0.610380907830146
  lightness: 0.11930901388361091
  saturation: 0.12771887429833118
  rhythmicContrast: 0.04936891418641968
purpose: []
title: Technology & Science
description: internet. artificial intelligence. scientific discoveries.
author:
  name: Kristoffer Rose Svarre
  url: 'https://www.linkedin.com/in/ksvarre'
  email: ksvarre@gmail.com
navigation:
  - name: Home
    url: 'https://think-like.me'
    type: external
  - name: Motivation & Personal Development
    url: 'http://development.think-like.me'
    type: external
  - name: 'Business, Innovation & Entrepreneurship'
    url: 'http://business.think-like.me'
    type: external
  - name: Crypto Economics & Blockchain Technology
    url: 'http://crypto.think-like.me'
    type: external
  - name: Portfolio & Accomplishments
    url: 'http://portfolio.think-like.me'
    type: external
  - name: About Me
    url: 'https://www.linkedin.com/in/ksvarre'
    type: external
content: []
github: true
url: 'https://ai.think-like.me/'
