typography_spectrum: 0.4510947629966137
color:
  saturation: 0.12771887429833118
  brandStrength: 0.610380907830146
  rhythmicContrast: 0.04936891418641968
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#725700'
    - '#FC2E8D'
    - '#E6B600'
  lightness: 0.11930901388361091
github: true
layout_spectrum: 0.23649111656619623
analytics:
  google: UA-79126334-1
author:
  name: Kristoffer Rose Svarre
  email: ksvarre@gmail.com
  url: 'https://www.linkedin.com/in/ksvarre'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c02f7dd-cadd-4c93-9798-509f44f543c5.png
name: Technology & Science
navigation:
  - name: Home
    url: 'http://think-like.me'
    type: external
  - name: Motivation & Personal Development
    url: 'http://development.think-like.me'
    type: external
  - name: 'Business, Innovation & Entrepreneurship'
    url: 'http://business.think-like.me'
    type: external
  - name: About Me
    url: 'https://www.linkedin.com/in/ksvarre'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ca9903b-91c3-40d6-88d6-7acabd1d6f61.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Technology & Science
content: []
description: internet. artificial intelligence. scientific discoveries.
purpose: []
